apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota
  namespace: mynamespace
spec:


#commands to check resourcequota
#kubectl create ns mynamespace
#kubectl get ns
#kubectl get pods -n mynamespace
#kubectl get resourcequota -n mynamespace
