apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
  labels:
    app: jenkins
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
      tolerations:
        - key: "colour"
          operator: "Equal"
          value: "red"
          effect: "NoSchedule"

#commands to create taint node
#kubectl get nodes
#kubectl taint node nodename colour=red:NoSchedule
#kubectl describe node nodename >>> To view taint info
#kubectl scale --replicas=4 deployment deploymentname  >> to scale the replica using command
