apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: mynamespace  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-all
  template:
    metadata:
      name: jenkins
      labels:
        app: label-all
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
#kubectl describe pod jenkins-deployment-55fc47bbc-24bpg -n mynamespace  >>> to get QOS Burstable when request resource uses more than limits resources then K8s used Qos as Busrstable
 
