apiVersion: v1
kind: Service
metadata:
  name: jenkins-node
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: podport
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005 
