apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-replicaset
  labels:
    app: my-jenkins
spec:
  replicas: 2 
  selector: 
    matchLabels:
      app: allpods 
  template: 
    metadata:
      name: jenkins-pod
      labels:
        app: allpods
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts

