apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: jenkins/jenkins:lts
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username


#kubectl create secret generic backend-user --from-literal=backend-username='backend-admin'
#kubectl exec -i -t env-single-secret -- /bin/sh -c 'echo $SECRET_USERNAME'
